
from __future__ import absolute_import

from swagger_client.api_client import ApiClient


class CustomApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_url_with_http_info(self, x_client_product_version, url):

        header_params = {}
        if x_client_product_version:
            header_params['X-Client-Product-Version'] = x_client_product_version 
        
        path_params = []
        query_params = []
        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.kartverket.sosi+json; version=1.0'])

        # Authentication setting
        auth_settings = ['basicAuth']

        response = self.api_client.request("GET", url)

        return response